language: node_js
node_js:
- node
branches:
  only:
    - master
install:
  - npm install -g @vue/cli
  - npm install -g firebase-tools
before_script:
  - npm run test:unit
script:
  - npm install
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN_PLAIN