dist: xenial
language: node_js
sudo: required
node_js:
- node
branches:
  only:
    - master
# install:
#   - npm install -g @vue/cli
#   - npm install -g firebase-tools
#   - npm install
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
  # - npm run test:unit
  - ./jarvis hello world
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN_PLAIN
