dist: trusty
sudo: required
language: python
python:
- '3.6'

script:
  - source set_variables.sh
after_success:
  - printenv
  - echo "printing image name"
  - echo ${IMAGE_NAME}

deploy:
  provider: script
  script: echo ${IMAGE_NAME} && echo "Inside deploy stage"
  # script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    # TODO need to be environment dependent
    all_branches: true
    condition: $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "stage"












# language: python
# python:
#   - "3.5"
# install:
#   - echo "Yay install"
#   - pip install requests

# script:
#   - echo "Yay script"
# after_success:
#   - chmod ugo+x ./deploy.py
#   - ./deploy.py