language: node_js

node_js:
- node
branches:
  only:
    - master
install:
  - npm install -g @vue/cli
  - npm install
before_script:
  - npm run test:unit
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: stage