language: node_js
node_js:
- node
branches:
  only:
    - master
install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "yes branch is master"
    else
      echo "no, branch is not master"
    fi
  # - npm install -g @vue/cli
  # - npm install -g firebase-tools
  # - npm install

before_script:
  # - npm run test:unit
  - echo "Inside before script"
script:
  # - npm run build
  - echo "inside script"
after_success:
  - echo "after success"
  # - firebase deploy --token $FIREBASE_TOKEN_PLAIN
